name: "CI for globoticket feature"
permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
  push:
      branches: [ "dependabot/*" ]
      paths:
      - 'frontend/**'
      - 'catalog/**'
      - 'ordering/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: setup dotnet
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: 6.0.x
      - name: restore dependancy 
        run: dotnet restore
      - name: build dot net
        run: dotnet build --no-restore
    
