name: "my app"
permissions: 
  actions: write
  contents: read

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'frontend/**'
    - 'backend/**'
    - 'ordering/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "checkout"
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
    - name: "setup .net"
      uses: actions/setup-dotnet@v4.3.0
    - name: "restore depedancy"
      run: dotnet restore
    - name: "dot net build"
      run: dotnet build
    - name: "test"
      run: dotnet test --no-build >> "$GITHUB_STEP_SUMMARY"
          
      
