name: test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: setup dot net
      uses: actions/setup-dotnet@v4.2.0
    - name: restore dependancy 
      run: dotnet restore
    - name: build dot net
      run: dotnet build --no-restore
    - name: dotnet test
      run: dotnet test -l:trx;LogFileName=TestOutput.xml >> $GITHUB_STEP_SUMMARY
    
  
